# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da47f9474b0c5f687bf1d906ac6a0c70c16f802a39ceb4204d097204a8d5923ce0fe64dd6b5e2967460e0bd42f0a6ecb7f40e6af8b5b4305061efeb41e2c1a86

test:
  secret_key_base: 1014d70b5919f75db5694754f2acf8ab8100d169f9f487cb06ce38d7739a15ee2f2a21edcd94a352792024b8d38d9dc787004d58e30669aa406c365d91862f52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
